# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e641e91196d816617b6b0cd93533714fe78819698e973858da666f9db3dce80430d2541b204e16c3e40bc971fcec41b0a101f03428fdbd4049156fee09a9bdc

test:
  secret_key_base: 3f5255d19e52453093fa6251d0c6da7390c03360f04ea40731951825d7b3d455fb38e4b39d4c6d2bbe0cad28b5c9d56367f1a5485c492ec96fae1bd9e31a5a1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
